export const ACTION = {
  ADD_COLUMN: 'ADD_COLUMN',
  INIT_DATA: 'INIT_DATA',
  TOGGLE_NEW_CARD: 'TOGGLE_NEW_CARD',
  DELETE_COLUMN: 'DELETE_COLUMN',
  MODIFY_CARD: 'MODIFY_CARD',
  ADD_CARD: 'ADD_CARD',
  DELETE_CARD: 'DELETE_CARD',
  CANCEL_ADDING_STATE: 'CANCEL_ADDING_STATE',
  MODIFY_COLUMN_TITLE: 'MODIFY_COLUMN_TITLE',
  TRANSFER_CARD: 'TRANSFER_CARD',
};
